spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  profiles:
    active: dev

server:
  error:
    include-stacktrace: never

security:
  jwt:
    duration: 2880
    seed : massou